# Generated by Django 4.1.7 on 2023-03-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_for_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
                ('desciption', models.TextField(verbose_name='Kurs haqida ma`lumot')),
                ('slider', models.ImageField(upload_to='course/course/slider/', verbose_name='Rasm')),
                ('author', models.CharField(max_length=150, verbose_name='Muallif')),
                ('type', models.CharField(choices=[('Bestseller', 'Ko`p sotilgan'), ('Recommended', 'Tavsiya etiladi'), ('Nothing', 'Oddiy')], default='Nothing', max_length=15, verbose_name='Kurs turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Chegirma')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chegirmadagi narxi')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category_for_course')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('section_title', models.CharField(max_length=150, verbose_name='Sarlavhasi')),
                ('section_number', models.PositiveIntegerField(default=1, verbose_name='Tartib nomeri')),
                ('section_type', models.CharField(choices=[('Not seen', 'Ko`rilmagan'), ('In progress', 'Jarayonda'), ('Reviewed', 'Ko`rilgan')], default='Not seen', max_length=20, verbose_name='Bo`lim turi')),
                ('is_public', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'Bo`lim',
                'verbose_name_plural': 'Bo`limlar',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='course/episode/file/', verbose_name='Fayl')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.section')),
            ],
            options={
                'verbose_name': 'Epizod',
                'verbose_name_plural': 'Epizodlar',
            },
        ),
    ]
