# Generated by Django 4.1.7 on 2023-03-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_comment',
            name='episode_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.episode', verbose_name='Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
