# Generated by Django 4.1.7 on 2023-03-13 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_video_comment_episode_id_alter_episode_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode_viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.episode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video ko`rilganligi',
                'verbose_name_plural': 'Video ko`rilganligi',
            },
        ),
    ]
