# Generated by Django 4.1.7 on 2023-03-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_episode_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(default=1, max_length=150, verbose_name='Slugi'),
            preserve_default=False,
        ),
    ]
