# Generated by Django 4.1.7 on 2023-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Not seen', 'Ko`rilmagan'), ('In progress', 'Jarayonda'), ('Reviewed', 'Ko`rilgan'), ('Not purchased', 'Sotib olinmagan')], default='Not seen', max_length=20, verbose_name='Bo`lim turi'),
        ),
    ]
