# Generated by Django 4.1.7 on 2023-03-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_purchased_course_is_finished_completed_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='user/user_profile/profile_pic/default-user-image.png', upload_to='user/user_profile/profile_pic/', verbose_name='Rasm'),
        ),
    ]
