# Generated by Django 4.1.7 on 2023-03-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
    ]
