# Generated by Django 4.1.7 on 2023-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='slug', max_length=250, verbose_name='Slugi'),
            preserve_default=False,
        ),
    ]
