# Generated by Django 4.1.7 on 2023-03-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='views',
            old_name='ip_address',
            new_name='device_id',
        ),
    ]
