# Generated by Django 4.1.7 on 2023-03-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_ip_address_views_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='ip_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ip manzili'),
        ),
        migrations.AlterField(
            model_name='views',
            name='device_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Qurilma manzili'),
        ),
    ]
