# Generated by Django 4.1.7 on 2023-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(default=1, max_length=150, verbose_name='Slugi'),
            preserve_default=False,
        ),
    ]
