# Generated by Django 4.1.7 on 2023-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='main/certificate/file/', verbose_name='Fayl'),
        ),
    ]
